name: 'Add Helm Repositories'
description: 'Add Bitnami and Secrets Store CSI Driver Helm repositories'

inputs:
  project_id:
    description: 'The project_id of the cluster'
    required: true
  cluster_name:
    description: 'The name of the cluster'
    required: true
  region:
    description: 'The region of the cluster'
    required: false
    default: us-west1
  sa-key:
    description: 'The key of the service account'
    required: true

runs:
  using: "composite"
  steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ inputs.project_id }}
          credentials_json: ${{ inputs.sa-key }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ inputs.project_id }}

      - name: Get GKE credentials
        id: get_gke_credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ inputs.cluster_name }}
          location: ${{ env.region }}
