name: 'Build and Push Docker Image to GCR'
description: 'Builds and pushes a Docker image to Google Cloud Artifact Registry'

inputs:
  dockerfile:
    required: true
    description: 'Dockerfile'
  dockerfile_path:
    required: true
    description: 'Path to docker file'
  image_name:
    required: true
    description: 'Name of the docker image'
  image_tag:
    required: true
    description: 'Tag of the docker image'
  github_user:
    required: true
    description: 'Github user to fetch packages'
  github_token:
    required: true
    description: 'Github token to fetch packages'
  set_latest:
    required: false
    description: Whether to set the latest tag (meant for releases)
    default: 'false'
  params:
    default: ''
    description: 'Parameters for docker building'


runs:
  using: "composite"
  steps:

    - name: Setup docker
      uses: docker/setup-buildx-action@v2

    - run: gcloud auth configure-docker gcr.io --quiet
      shell: bash

    - run: |
        cd ${{ inputs.dockerfile_path }}
        DOCKER_BUILDKIT=1 docker build . \
        -f ${{ inputs.dockerfile }} \
        --tag gcr.io/nanoclinic-common/${{ inputs.image_name }}:${{ inputs.image_tag }} \
        --build-arg GITHUB_USER=${{ inputs.github_user }} \
        --build-arg GITHUB_TOKEN=${{ inputs.github_token }} \
        ${{ inputs.params }}
      shell: bash

    - run: docker push gcr.io/nanoclinic-common/${{ inputs.image_name }}:${{ inputs.image_tag }}
      shell: bash

    - run: docker push gcr.io/nanoclinic-common/${{ inputs.image_name }}:latest
      shell: bash
      if: ${{ inputs.set_latest == 'true' }}

    - run: |
        docker tag gcr.io/nanoclinic-common/${{ inputs.image_name }}:${{ inputs.image_tag }} gcr.io/nanoclinic-common/${{ inputs.image_name }}:${{ github.run_id }}.${{ github.run_number }}
        docker push gcr.io/nanoclinic-common/${{ inputs.image_name }}:${{ github.run_id }}.${{ github.run_number }}
      shell: bash