
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migration
  namespace: {{ .Release.Namespace }}
{{- include "migration.labels" . | indent 2 }}
{{- include "common.annotations" . | indent 2 }}
spec:
  template:
    metadata:
      {{- include "migration.labels" . | indent 6 }}
      {{- include "migration.annotations" . | indent 6 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.serviceAccount }}
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: {{ .Release.Name }}
          image: {{ printf "%s:%s" .Values.image .Values.image_tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
          - containerPort: {{ .Values.internalPort }}
        {{- if eq .Values.debug true }}
          - containerPort: {{ .Values.debugPort }}
        {{- end }}
      {{- if .Values.probe_config }}
        {{- if .Values.startupProbe }}
          startupProbe:
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            {{- include "probe" . | indent 12}}
        {{- end }}
        {{- if .Values.livenessProbe }}
          livenessProbe:
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            {{- include "probe" . | indent 12}}
        {{- end }}
        {{- if .Values.readinessProbe }}
          readinessProbe:
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            {{- include "probe" . | indent 12}}
        {{- end }}
      {{- end }}
        {{- if ne .Values.debug true }}
          resources:
            requests:
              cpu: {{ .Values.min_cpu }}
            limits:
              cpu: {{ .Values.max_cpu }}
        {{- end }}
        {{- if eq .Values.debug true }}
          command:
            {{ range $arg:= .Values.migration.command }}
            - {{$arg | quote}}
            {{- end }}
        {{- end }}
          env:
        {{- range $key,$value:= .Values.parameters }}
          - name: {{ upper $key | replace "-" "_" }}
            value: {{ $value | quote }}
        {{- end }}