
{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migration
  namespace: {{ .Release.Namespace }}
  {{- include "migration.labels" . | indent 2 }}
  {{- include "migration.annotations" . | indent 2 }}
spec:
  template:
    metadata:
      {{- include "migration.labels" . | indent 6 }}
      {{- include "migration.annotations" . | indent 6 }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.serviceAccount }}
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: {{ .Release.Name }}
          image: {{ printf "%s:%s" .Values.image .Values.image_tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
          - containerPort: {{ .Values.internalPort }}
        {{- if eq .Values.debug.enabled true }}
          - containerPort: {{ .Values.debug.port }}
        {{- end }}
        {{- if ne .Values.debug.enabled true }}
          resources:
            requests:
              cpu: {{ .Values.min_cpu }}
            limits:
              cpu: {{ .Values.max_cpu }}
        {{- end }}
        {{- if eq .Values.debug.enabled true }}
          command:
            {{ range $arg:= .Values.debug.command }}
            - {{$arg | quote}}
            {{- end }}
        {{- else }}
          command:
            {{ range $arg:= .Values.migration.command }}
            - {{$arg | quote}}
            {{- end }}
        {{- end }}
          env:
            - name: ENV
              value: {{ .Values.global.env }}
            - name: PROJECT_ID
              value: {{ .Values.global.project_id }}
          {{- range $key,$value:= .Values.parameters }}
            {{- if $.Values.env_prefix }}
            - name: {{ printf "%s%s" (upper $.Values.env_prefix) (upper $key | replace "-" "_") }}
            {{- else }}
            - name: {{ printf "%s" (upper $key | replace "-" "_") }}
            {{- end }}
              value: {{ $value | quote }}
          {{- end }}
{{- end }}