{{- if eq .Values.expose true }}
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ printf ".Release.Name-route"}}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - kind: Gateway
      name: {{printf "api-gateway-%s" .Release.Namespace }}
  hostnames:
    - {{ .Values.global.hostname}}
  rules:
    - matches:
      - path:
          type: PathPrefix
        {{- if eq .Values.route "" }}
          value: {{ .Release.Name }}
        {{- else }}
          value: {{ printf "/%s" .Values.route }}
        {{- end }}
      filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
      backendRefs:
      - name: {{ .Release.Name }}
        port: {{  $.Values.internalPort }}
    {{- range $key,$value:= .Values.redirects }}
      - matches:
        - path:
            type: PathPrefix
            value: {{ $key }}
        filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: {{ $value }}
        backendRefs:
        - name: {{ .Release.Name }}
          port: {{  $.Values.internalPort }}
    {{- end }}
{{- end }}