apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "sa.annotations" . | indent 2 }}
  {{- include "all.labels" . | indent 2 }}
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Release.Namespace }}