apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
{{- include "all.labels" . | indent 2 }}
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: {{ .Release.Name }}-port
    protocol: TCP
    port: {{ .Values.internalPort }}
    targetPort: {{ .Values.internalPort }}
{{- if eq .Values.debug true }}
  - name: {{ .Release.Name }}-debug-port
    protocol: TCP
    port: {{ .Values.internalPort }}
    targetPort: {{ .Values.internalPort }}
{{- end }}

---

{{- if and (eq .Values.expose true) (ne .Values.health_endpoint nil) }}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Release.Name }}-healthcheck
spec:
  default:
    checkIntervalSec: 1
    timeoutSec: 1
    healthyThreshold: 1
    unhealthyThreshold: 1
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: {{ .Values.internalPort }}
        host: "gcp-lb-health-check"
        requestPath: {{ .Values.health_endpoint }}
  targetRef:
    group: ""
    kind: Service
    name: {{ .Release.Name }}
{{- end }}
