apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s" $app }}
  annotations:
  namespace: {{ .Release.Namespace }}
{{- include "labels.all" . | indent 2 }}
    app: {{- $app }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.internalPort }}
    targetPort: {{ .Values.internalPort }}
    protocol: TCP
    name: {{- printf "%s-port" $app }}
{{- if eq .Values.debug true }}
  - port: {{ .Values.debugPort }}
    targetPort: {{ .Values.debugPort }}
    protocol: TCP
    name: {{- printf "%s-debug-port" $app }}
{{- end }}
  selector:
    app: {{ printf "%s" $app}}

---

{{- if .Values.routes }}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ $app }}-healthcheck
spec:
  default:
    checkIntervalSec: 1
    timeoutSec: 1
    healthyThreshold: 1
    unhealthyThreshold: 1
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: {{ .Values.internalPort }}
        host: "gcp-lb-health-check"
        requestPath: {{ .Values.health_endpoint }}
  targetRef:
    group: ""
    kind: Service
    name: {{ $app }}
{{- end }}
