
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ printf "%s@%s.iam.gserviceaccount.com" .Values.serviceAccount .Values.global.project_id }}
{{- include "labels.all" . | indent 2 }}
  name: {{ $app }}
  namespace: {{ .Release.Namespace }}