
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ printf "%s@%s.iam.gserviceaccount.com" .Values.serviceAccount .Values.global.project_id | quote }}
{{- include "all.labels" . | indent 2 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}