name: 'Terraform Plan Composite Action'
description: 'Steps to build the terraform plan'

inputs:
  env:
    description: 'Environment name'
    required: true
  github_token:
    description: 'Auth Token to fetch private terraform modules'
    required: true
  branch:
    description: 'Terraform code branch name'
    required: true
  working-directory:
    description: 'Working directory'
    required: false
    default: 'ci-cd/terraform/gcp'
  publish_functions:
    description: 'Publish Cloud Functions zip files'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:

    - name: Adjust git config to terraform
      shell: bash
      id: terraform_config
      run: |
        git config --global url."https://oauth2:${{ inputs.github_token }}@github.com".insteadOf https://github.com
        dir_basename=$(basename "${{ inputs.working-directory }}")
        echo "dir_basename=${dir_basename}" | tee -a $GITHUB_OUTPUT

    - name: Terraform init
      run: terraform init
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Terraform select workspace
      run: terraform workspace select ${{ inputs.env }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Terraform validate
      run: terraform validate
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Terraform plan
      run: terraform plan -var-file "settings_${{ inputs.env }}.tfvars" -out "${{ inputs.branch }}_${{ inputs.env }}.tfplan"
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Upload Terraform plan
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.terraform_config.outputs.dir_basename }}_${{ inputs.branch }}_${{ inputs.env }}.tfplan
        path: ${{ inputs.working-directory }}/${{ inputs.branch }}_${{ inputs.env }}.tfplan
